#
#server:
#  port: 8083
#spring:
#  application:
#    name: ms-transacciones
#  datasource:
#    url: jdbc:mysql://localhost:3306/transacciones_db
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#  security:
#    user:
#      name: user
#      password: password
#springdoc:
#  swagger-ui:
#    path: /doc/swagger-ui.html
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka
spring:
  application:
    name: ms-transacciones # cambia según el microservicio
  cloud:
    config:
      uri: http://localhost:8888

