#spring.datasource.url=jdbc:mysql://localhost:3306/contabilidad_db
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.application.name=ms-clientes
#server.port=8082
#

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clientes_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
