server:
  port: 8085

spring:
  application:
    name: ms-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        ssl:
          enabled: false
      routes:
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/usuarios/**
        - id: ms-clientes
          uri: lb://ms-clientes
          predicates:
            - Path=/clientes/**
        - id: ms-transacciones
          uri: lb://ms-transacciones
          predicates:
            - Path=/transactions/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    fetchRegistry: true
    registerWithEureka: true
