server:
  port: 8085

spring:
  application:
    name: ms-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        ssl:
          enabled: false
      routes:
        - id: pap-cursos
          uri: lb://pap-cursos
          predicates:
            - Path=/cursos/**
        - id: pap-estudiantes
          uri: lb://pap-estudiantes
          predicates:
            - Path=/estudiantes/**
        - id: pap-matriculas
          uri: lb://pap-matriculas
          predicates:
            - Path=/matriculas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    fetchRegistry: true
    registerWithEureka: true
