server:
  port: 8085

spring:
  application:
    name: ms-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: pap-cursos
          uri: lb://pap-cursos
          predicates:
            - Path=/cursos/**
        - id: pap-estudiantes
          uri: lb://pap-estudiantes
          predicates:
            - Path=/estudiantes/**
        - id: pap-matricula
          uri: lb://pap-matricula
          predicates:
            - Path=/matriculas/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
      instance:
        #hostname: localhost
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    fetchRegistry: true
    registerWithEureka: true
