
server:
  port: 8082

spring:
  application:
    name: ms-clientes
  datasource:
    url: jdbc:postgresql://localhost:5432/estudiantes_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
