server:
  port: 8083
spring:
  application:
    name: pap-matricula
  datasource:
    url: jdbc:mysql://localhost:3306/matricula_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: user
      password: password
springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html

# Configuración para Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

# Configuración para Resilience4J Circuit Breaker
resilience4j.circuitbreaker:
  instances:
    papCursosCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
