server:
  port: 8090  # Configura el puerto en el que se ejecutará Eureka

spring:
  application:
    name: eureka-server  # Nombre del servicio de Eureka
  cloud:
    config:
      enabled: false
eureka:
  client:
    registerWithEureka: false  # No necesita registrarse en Eureka
    fetchRegistry: false  # No necesita obtener el registro
  server:
    enableSelfPreservation: false  # Deshabilitar la auto-preservación (solo en desarrollo)
